export const QUESTION_CARDS = [
  { text: "Người lặng im / người hay nói?", depth: 1, type: "Vui mở đầu", icon: "🌿" },
  { text: "Kể 1 điều ấn tượng hoặc thích nhất về đối phương?", depth: 2, type: "Dịu dàng", icon: "💕" },
  { text: "Điều gì của đối phương khiến bạn chưa hài lòng?", depth: 4, type: "Thành thật", icon: "🫧" },
  { text: "Điều gì khiến bạn muốn đi tiếp và gắn bó với đối phương?", depth: 4, type: "Gắn bó", icon: "🧡" },
  { text: "Con trai hay con gái nên là người chủ động?", depth: 2, type: "Quan điểm", icon: "🎲" },
  { text: "Bạn thấy mình hợp nhau vì điều gì?", depth: 3, type: "Kết nối", icon: "🧩" },
  { text: "Những điểm xấu nào mà bạn muốn được thông cảm?", depth: 4, type: "Mở lòng", icon: "🕯️" },
  { text: "Nếu như bây giờ mà em tắt đèn, anh muốn làm gì với em?", depth: 3, type: "Lãng mạn", icon: "🌙" },
  { text: "Câu nói nào của đối phương khiến bạn nhớ nhất?", depth: 2, type: "Kỷ niệm", icon: "💌" },
  { text: "Điểm khác biệt giữa đối phương và người khác là gì?", depth: 3, type: "Riêng biệt", icon: "✨" },
  { text: "Có nơi nào mà bạn cực kỳ muốn dẫn đối phương đi không?", depth: 1, type: "Mơ mộng", icon: "🗺️" },
  { text: "Việc nhà mà bạn muốn được làm cùng nhau nhất khi ở chung là gì?", depth: 2, type: "Đời thường", icon: "🏡" },
  { text: "Bạn cảm thấy tính cách, lối sống của hai chúng ta đang bù trừ cho nhau hay đang giống nhau?", depth: 3, type: "Thấu hiểu", icon: "☯️" },
  { text: "1, 2, 3… Cùng nói ra một địa điểm.", depth: 1, type: "Nhanh vui", icon: "📍" },
  { text: "1, 2, 3… Cùng nói ra một món ăn.", depth: 1, type: "Nhanh vui", icon: "🍜" },
  { text: "Đâu là điều quan trọng nhất với bạn khi yêu và xác định cưới?", depth: 5, type: "Tương lai", icon: "💍" },
  { text: "Nếu 1 ngày bạn không liên lạc được với người kia thì bạn sẽ làm gì?", depth: 3, type: "Tình huống", icon: "📵" },
  { text: "Bạn nhận ra mình thích đối phương là từ bao giờ hoặc khoảnh khắc nào?", depth: 3, type: "Rung động", icon: "💗" },
  { text: "Nếu trong thời gian yêu nhau mà bạn nhận ra đối phương không phải là người mình muốn cưới thì bạn sẽ làm gì?", depth: 5, type: "Câu sâu", icon: "🌊" },
  { text: "Nếu mình cãi nhau thì bạn sẽ làm gì?", depth: 4, type: "Xung đột", icon: "🤍" },
  { text: "Có bài học về tình cảm nào ở quá khứ mà bạn đã học được và muốn chia sẻ không?", depth: 5, type: "Quá khứ", icon: "📖" },
  { text: "Điều gì trong cuộc sống sẽ dễ khiến bạn áp lực nhất?", depth: 4, type: "Áp lực", icon: "☁️" },
  { text: "Kể ra 1 điểm tốt của tất cả những người bạn thân của bạn, mỗi người bạn chỉ kể 1 điểm.", depth: 2, type: "Bạn bè", icon: "👥" },
  { text: "Nếu được chọn 1 siêu năng lực thì đó là gì?", depth: 1, type: "Vui nhẹ", icon: "⚡" },
  { text: "Điều gì là ưu tiên số 1 của bạn?", depth: 4, type: "Ưu tiên", icon: "🎯" },
  { text: "Nếu được xóa 1 ký ức, thì đó là gì?", depth: 5, type: "Rất sâu", icon: "🫧" },
  { text: "Một bộ phim mà bạn muốn xem cùng đối phương?", depth: 1, type: "Hẹn hò", icon: "🎬" },
  { text: "Nếu được quay lại buổi hẹn đầu tiên, bạn muốn thay đổi điều gì?", depth: 2, type: "Kỷ niệm", icon: "🕰️" },
  { text: "Một điều nhỏ đối phương làm khiến bạn thấy được yêu là gì?", depth: 3, type: "Yêu thương", icon: "🌷" },
  { text: "Khi buồn, bạn muốn được an ủi bằng cách nào?", depth: 4, type: "Chăm sóc", icon: "🤲" },
  { text: "Bạn sợ điều gì nhất trong một mối quan hệ lâu dài?", depth: 5, type: "Nỗi sợ", icon: "🌫️" },
  { text: "Một thói quen nào của bạn mà bạn mong đối phương kiên nhẫn với nó?", depth: 4, type: "Mở lòng", icon: "🧸" },
  { text: "Nếu có một ngày rảnh hoàn toàn cho hai người, bạn muốn làm gì?", depth: 1, type: "Hẹn hò", icon: "🌤️" },
  { text: "Điều gì khiến bạn cảm thấy an toàn khi ở cạnh đối phương?", depth: 4, type: "An toàn", icon: "🛟" },
  { text: "Bạn nghĩ tình yêu cần nhiều lãng mạn hơn hay nhiều trách nhiệm hơn?", depth: 3, type: "Quan điểm", icon: "⚖️" },
  { text: "Một lời xin lỗi như thế nào sẽ khiến bạn thấy thật lòng?", depth: 4, type: "Xung đột", icon: "🕊️" },
  { text: "Bạn muốn hai người giữ truyền thống nhỏ nào mỗi tuần hoặc mỗi tháng?", depth: 2, type: "Nghi thức", icon: "📅" },
  { text: "Nếu phải mô tả tình yêu của hai người bằng một màu sắc, bạn chọn màu gì?", depth: 1, type: "Mơ mộng", icon: "🎨" },
  { text: "Điều gì làm bạn dễ bị tổn thương nhưng ít khi nói ra?", depth: 5, type: "Rất sâu", icon: "🥀" },
  { text: "Bạn có kỳ vọng nào về tương lai mà sợ nói ra sẽ tạo áp lực không?", depth: 5, type: "Tương lai", icon: "🌌" },
  { text: "Khi cãi nhau, điều gì đối phương tuyệt đối không nên làm?", depth: 4, type: "Ranh giới", icon: "🚧" },
  { text: "Bạn muốn được đối phương công nhận ở điểm nào nhất?", depth: 4, type: "Công nhận", icon: "🏅" },
  { text: "Một điều bạn từng hiểu lầm về đối phương là gì?", depth: 3, type: "Thấu hiểu", icon: "🔍" },
  { text: "Nếu hai người cùng tiết kiệm cho một mục tiêu, bạn muốn đó là gì?", depth: 3, type: "Tương lai", icon: "🏦" },
  { text: "Bạn muốn tình yêu của mình giống một bộ phim, bài hát hay mùa nào? Vì sao?", depth: 2, type: "Mơ mộng", icon: "🎧" },
  { text: "Điều gì khiến bạn cảm thấy mình đang được lắng nghe thật sự?", depth: 4, type: "Lắng nghe", icon: "👂" },
  { text: "Một bí mật nhỏ, dễ thương hoặc hơi ngại, mà bạn muốn kể hôm nay là gì?", depth: 3, type: "Bí mật", icon: "🤫" },
  { text: "Nếu ngày mai phải xa nhau một thời gian, bạn muốn dặn đối phương điều gì?", depth: 5, type: "Xa cách", icon: "✈️" },
  { text: "Bạn nghĩ hai người cần học thêm điều gì để yêu nhau tốt hơn?", depth: 4, type: "Trưởng thành", icon: "🌱" },
  { text: "Kết thúc buổi chơi hôm nay, bạn muốn nói một câu thật lòng nào với đối phương?", depth: 5, type: "Lời nhắn", icon: "💞" }
];
